spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:mysql://pre-project-seb44-036.cmcgfzxicpzn.ap-northeast-2.rds.amazonaws.com:13306/test
    username: ${DATABASE_USERNAME}  # MySQL 사용자 이름
    password: ${DATABASE_PASSWORD}  # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    seb44pre036:
      qna: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 100
  refresh-token-expiration-minutes: 180
config:
  domain: https://seb-44-pre-036.web.app